#!/usr/bin/env bash
# This script installs Nginx and configures a 301 redirection

# Update package lists
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Add the redirection configuration to the Nginx default site configuration
sudo sed -i '/server_name _;/a \ \n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart

# Output the status of Nginx to ensure it's running
sudo service nginx status
