#!/usr/bin/env bash
# This script installs Nginx and configures a custom 404 page

# Update package lists
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Create the custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Modify the Nginx default site configuration to use the custom 404 page
sudo sed -i '/server_name _;/a \ \n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart

# Output the status of Nginx to ensure it's running
sudo service nginx status
