#!/usr/bin/env bash
# Install nginx server, Configure index page, add a custome Header

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend younes
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 379988-web-01 18.206.208.103:80 check
    server 379988-web-02 52.201.192.84:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
