#!/usr/bin/env bash
# this Script:
# Create a file contain the script PID
# Display some texts
# delete the file & terminate
# receiving signals

echo $$ > /var/run/myscript.pid

trap 'echo "I hate the kill command"; exit 1' SIGTERM

trap 'echo "Y U no love me?!"; exit 1' SIGINT

trap 'rm -f /var/run/myscript.pid; exit 0' SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 1
done

