#!/usr/bin/env bash
# This Script Display the FizzBuzz

i=1

while [ $i -ne 101 ];
do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $((i % 5)) -eq 0 ]; then
		echo "Buzz"
	elif [ $((i % 3)) -eq 0 ]; then
		echo "Fizz"
	else
		echo "$i"
	fi		
	((i++))
done
